# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
#  server:
#    build:
#      context: .
#    ports:
#      - 5555:5555
#    depends_on:
#      db:
#        condition: service_healthy
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tiger
      - POSTGRES_USER=scott
      - POSTGRES_DB=led_manager
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "db"]
      interval: 10s
      timeout: 5s
      retries: 5
